name: "CI/CD Pipeline for LMS Front-End"
on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the latest commit
        uses: actions/checkout@v3

      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing SASS
        run: npm install -g sass

      - name: 'Compiling *.scss to *.css'
        run: sass scss:css

      - name: Creating the dist directory
        run: mkdir dist

      - name: Copying everything to dist directory
        run: cp -r css pages js index.html dist/

      - name: Creating zip file to deployment
        run: zip -r dist.zip dist/
      
      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCE_PROJECT }}

      - name: Setting up the gcloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploying the dist.zip
        run: gcloud compute scp --zone="asia-south1-a" dist.zip root@dep9-vm:/opt/apache/apache-tomcat-10.1.1/webapps/lms

      - name: Cleaning up
        run: gcloud compute ssh --zone="asia-south1-a" dep9-vm --command="sudo rm -r /opt/apache/apache-tomcat-10.1.1/webapps/lms/css /opt/apache/apache-tomcat-10.1.1/webapps/lms/pages /opt/apache/apache-tomcat-10.1.1/webapps/lms/js /opt/apache/apache-tomcat-10.1.1/webapps/lms/index.html"

      - name: Extracting the dist.zip
        run: gcloud compute ssh --zone="asia-south1-a" dep9-vm --command="sudo unzip dist.zip"